[tasks.watch]
run_task = [
    { name = ["clippy", "test"] }
]
watch = true

[tasks.clippy]
command = "cargo"
args = ["clippy"]

[tasks.test]
commnad = "cargo"
args = ["test"]

[tasks.run]
command = "cargo"
args = ["run"]