[package]
name = "cat_rust"
version = "0.1.0"
edition = "2020"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
linux = "0.0.1"